dist: trusty
sudo: required
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
addons:
   apt:
      sources:
         - google-chrome
      packages:
         - google-chrome-stable
before_script:
  - npm install
script:
  - google-chrome --version
  - npm run test:ci
