dist: trusty
addons:
  chrome: stable
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
before_script:
  - yarn
script:
  - google-chrome-stable --version
  - yarn run test:ci
